# GitHub Dependabot Configuration
version: 2
updates:
  # Enable dependency updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  # Enable updates for npm dependencies
  - package-ecosystem: 'npm'
    directory: '/' # Change this if package.json is in a subdirectory
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: 'eslint'
        versions: ['<8.0.0'] # Example: Ignore major updates below v8

  # Enable updates for GitHub Actions workflows (if using CI/CD)
  - package-ecosystem: 'github-actions'
    directory: '/.github/workflows'
    schedule:
      interval: 'daily'
